// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1294: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1295: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1296: (x0,x1) => x0.createElement(x1),
      _1297: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1299: (x0,x1) => x0.getAttribute(x1),
      _1303: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1304: (x0,x1) => x0.canShare(x1),
      _1305: (x0,x1) => x0.share(x1),
      _1307: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1308: (x0,x1) => ({files: x0,text: x1}),
      _1309: (x0,x1) => ({files: x0,title: x1}),
      _1310: x0 => ({files: x0}),
      _1311: (x0,x1) => ({title: x0,text: x1}),
      _1312: x0 => ({text: x0}),
      _1313: x0 => x0.click(),
      _1314: x0 => x0.remove(),
      _1315: () => ({}),
      _1316: (x0,x1,x2) => new File(x0,x1,x2),
      _1318: (x0,x1,x2,x3,x4,x5) => ({clientId: x0,scope: x1,redirectURI: x2,state: x3,nonce: x4,usePopup: x5}),
      _1319: x0 => globalThis.AppleID.auth.init(x0),
      _1320: () => globalThis.AppleID.auth.signIn(),
      _1328: x0 => x0.authorization,
      _1329: x0 => x0.user,
      _1330: x0 => x0.error,
      _1332: x0 => x0.code,
      _1333: x0 => x0.id_token,
      _1334: x0 => x0.state,
      _1335: x0 => x0.email,
      _1336: x0 => x0.name,
      _1337: x0 => x0.firstName,
      _1338: x0 => x0.lastName,
      _1348: (x0,x1) => x0.item(x1),
      _1349: (x0,x1) => x0.querySelector(x1),
      _1357: (x0,x1) => x0.appendChild(x1),
      _1358: (x0,x1) => x0.item(x1),
      _1359: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1359(f,arguments.length,x0) }),
      _1360: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1361: x0 => globalThis.URL.createObjectURL(x0),
      _1362: (x0,x1) => x0.append(x1),
      _1363: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1363(f,arguments.length,x0) }),
      _1364: (x0,x1) => x0.getItem(x1),
      _1365: (x0,x1) => x0.removeItem(x1),
      _1366: (x0,x1,x2) => x0.setItem(x1,x2),
      _1422: (x0,x1) => x0.debug(x1),
      _1426: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1430: (x0,x1) => x0.key(x1),
      _1431: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1432: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1433: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1434: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1435: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1436: (x0,x1) => x0.getRandomValues(x1),
      _1437: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1438: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1440: (x0,x1) => x0.initialize(x1),
      _1444: x0 => x0.disableAutoSelect(),
      _1446: Date.now,
      _1448: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1449: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1450: () => new Error().stack,
      _1451: () => typeof dartUseDateNowForTicks !== "undefined",
      _1452: () => 1000 * performance.now(),
      _1453: () => Date.now(),
      _1454: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1455: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1456: () => new WeakMap(),
      _1457: (map, o) => map.get(o),
      _1458: (map, o, v) => map.set(o, v),
      _1459: (exn) => exn.toString(),
      _1460: (exn) => exn.stack,
      _1461: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1462: x0 => new WeakRef(x0),
      _1463: x0 => x0.deref(),
      _1464: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1464(f,arguments.length,x0) }),
      _1465: x0 => new FinalizationRegistry(x0),
      _1470: () => globalThis.WeakRef,
      _1471: () => globalThis.FinalizationRegistry,
      _1473: x0 => x0.call(),
      _1474: s => JSON.stringify(s),
      _1475: s => printToConsole(s),
      _1476: (o, p, r) => o.replaceAll(p, () => r),
      _1477: (o, p, r) => o.replace(p, () => r),
      _1478: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1479: s => s.toUpperCase(),
      _1480: s => s.trim(),
      _1481: s => s.trimLeft(),
      _1482: s => s.trimRight(),
      _1483: (string, times) => string.repeat(times),
      _1484: Function.prototype.call.bind(String.prototype.indexOf),
      _1485: (s, p, i) => s.lastIndexOf(p, i),
      _1486: (string, token) => string.split(token),
      _1487: Object.is,
      _1490: (o, t) => typeof o === t,
      _1491: (o, c) => o instanceof c,
      _1492: o => Object.keys(o),
      _1495: (o, a) => o + a,
      _1522: x0 => new Array(x0),
      _1524: x0 => x0.length,
      _1526: (x0,x1) => x0[x1],
      _1527: (x0,x1,x2) => { x0[x1] = x2 },
      _1530: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1532: x0 => new Int8Array(x0),
      _1533: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1535: x0 => new Uint8ClampedArray(x0),
      _1537: x0 => new Int16Array(x0),
      _1539: x0 => new Uint16Array(x0),
      _1541: x0 => new Int32Array(x0),
      _1543: x0 => new Uint32Array(x0),
      _1545: x0 => new Float32Array(x0),
      _1547: x0 => new Float64Array(x0),
      _1571: x0 => x0.random(),
      _1572: (x0,x1) => x0.getRandomValues(x1),
      _1573: () => globalThis.crypto,
      _1574: () => globalThis.Math,
      _1587: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1588: (handle) => clearTimeout(handle),
      _1589: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1590: (handle) => clearInterval(handle),
      _1591: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1592: () => Date.now(),
      _1593: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1594: (x0,x1) => x0.exec(x1),
      _1595: (x0,x1) => x0.test(x1),
      _1596: x0 => x0.pop(),
      _1598: o => o === undefined,
      _1600: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1602: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1603: o => o instanceof RegExp,
      _1604: (l, r) => l === r,
      _1605: o => o,
      _1606: o => o,
      _1607: o => o,
      _1608: b => !!b,
      _1609: o => o.length,
      _1611: (o, i) => o[i],
      _1612: f => f.dartFunction,
      _1613: () => ({}),
      _1614: () => [],
      _1616: () => globalThis,
      _1617: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1618: (o, p) => p in o,
      _1619: (o, p) => o[p],
      _1620: (o, p, v) => o[p] = v,
      _1621: (o, m, a) => o[m].apply(o, a),
      _1623: o => String(o),
      _1624: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1625: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1625(f,arguments.length,x0) }),
      _1626: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1626(f,arguments.length,x0,x1) }),
      _1627: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1628: o => [o],
      _1629: (o0, o1) => [o0, o1],
      _1630: (o0, o1, o2) => [o0, o1, o2],
      _1631: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1632: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1633: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1636: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1637: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1638: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1639: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1640: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1641: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1642: x0 => new ArrayBuffer(x0),
      _1643: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1645: x0 => x0.index,
      _1646: x0 => x0.groups,
      _1647: x0 => x0.flags,
      _1648: x0 => x0.multiline,
      _1649: x0 => x0.ignoreCase,
      _1650: x0 => x0.unicode,
      _1651: x0 => x0.dotAll,
      _1652: (x0,x1) => { x0.lastIndex = x1 },
      _1653: (o, p) => p in o,
      _1654: (o, p) => o[p],
      _1655: (o, p, v) => o[p] = v,
      _1656: (o, p) => delete o[p],
      _1657: x0 => x0.exports,
      _1658: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1659: x0 => x0.instance,
      _1662: x0 => x0.buffer,
      _1665: x0 => x0.arrayBuffer(),
      _1667: x0 => x0.sqlite3_initialize(),
      _1670: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1685: (x0,x1) => x0.sqlite3_finalize(x1),
      _1721: (x0,x1) => x0.sqlite3session_delete(x1),
      _1725: (x0,x1) => x0.sqlite3changeset_finalize(x1),
      _1736: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1740: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1751: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1751(f,arguments.length,x0) }),
      _1752: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1752(f,arguments.length,x0,x1) }),
      _1753: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1753(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1754: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1754(f,arguments.length,x0,x1,x2) }),
      _1755: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1755(f,arguments.length,x0,x1,x2,x3) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1756(f,arguments.length,x0,x1,x2,x3) }),
      _1757: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1757(f,arguments.length,x0,x1,x2) }),
      _1758: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1758(f,arguments.length,x0,x1) }),
      _1759: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1759(f,arguments.length,x0,x1) }),
      _1760: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1760(f,arguments.length,x0) }),
      _1761: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1761(f,arguments.length,x0,x1,x2,x3) }),
      _1762: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1762(f,arguments.length,x0,x1,x2,x3) }),
      _1763: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1763(f,arguments.length,x0,x1) }),
      _1764: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1764(f,arguments.length,x0,x1) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1765(f,arguments.length,x0,x1) }),
      _1766: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1766(f,arguments.length,x0,x1) }),
      _1767: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1767(f,arguments.length,x0,x1) }),
      _1768: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1768(f,arguments.length,x0,x1) }),
      _1769: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1769(f,arguments.length,x0) }),
      _1770: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1770(f,arguments.length,x0) }),
      _1771: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1771(f,arguments.length,x0) }),
      _1772: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1772(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1773: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1773(f,arguments.length,x0,x1,x2,x3) }),
      _1774: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1774(f,arguments.length,x0,x1,x2,x3) }),
      _1775: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1775(f,arguments.length,x0,x1,x2,x3) }),
      _1776: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1776(f,arguments.length,x0,x1) }),
      _1777: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1777(f,arguments.length,x0,x1) }),
      _1778: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1778(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1779: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1779(f,arguments.length,x0,x1) }),
      _1780: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1780(f,arguments.length,x0,x1) }),
      _1781: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1781(f,arguments.length,x0,x1,x2) }),
      _1785: x0 => new URL(x0),
      _1786: (x0,x1) => new URL(x0,x1),
      _1787: (x0,x1) => globalThis.fetch(x0,x1),
      _1788: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1790: (x0,x1) => x0.error(x1),
      _1791: (x0,x1) => new SharedWorker(x0,x1),
      _1792: x0 => new Worker(x0),
      _1793: () => new MessageChannel(),
      _1794: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1794(f,arguments.length,x0) }),
      _1795: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1796: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1796(f,arguments.length,x0) }),
      _1797: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1797(f,arguments.length,x0) }),
      _1810: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1811: (x0,x1,x2) => x0.open(x1,x2),
      _1812: x0 => ({autoIncrement: x0}),
      _1813: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1814: x0 => ({unique: x0}),
      _1815: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1816: (x0,x1) => x0.createObjectStore(x1),
      _1817: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1817(f,arguments.length,x0) }),
      _1819: (x0,x1,x2) => x0.transaction(x1,x2),
      _1820: (x0,x1) => x0.objectStore(x1),
      _1822: (x0,x1) => x0.index(x1),
      _1823: x0 => x0.openKeyCursor(),
      _1824: (x0,x1) => x0.getKey(x1),
      _1825: (x0,x1) => ({name: x0,length: x1}),
      _1826: (x0,x1) => x0.put(x1),
      _1827: (x0,x1) => x0.get(x1),
      _1828: (x0,x1) => x0.openCursor(x1),
      _1829: x0 => globalThis.IDBKeyRange.only(x0),
      _1830: (x0,x1,x2) => x0.put(x1,x2),
      _1831: (x0,x1) => x0.update(x1),
      _1832: (x0,x1) => x0.delete(x1),
      _1835: x0 => x0.name,
      _1836: x0 => x0.length,
      _1841: x0 => x0.continue(),
      _1842: () => globalThis.indexedDB,
      _1855: x0 => globalThis.BigInt(x0),
      _1856: x0 => globalThis.Number(x0),
      _1875: x0 => globalThis.Object.keys(x0),
      _1876: x0 => x0.length,
      _1877: () => new XMLHttpRequest(),
      _1878: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1882: x0 => x0.send(),
      _1884: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1884(f,arguments.length,x0) }),
      _1885: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1885(f,arguments.length,x0) }),
      _1890: (x0,x1) => x0.item(x1),
      _1891: (x0,x1) => x0.removeChild(x1),
      _1893: x0 => ({type: x0}),
      _1894: (x0,x1) => new Blob(x0,x1),
      _1896: () => new FileReader(),
      _1897: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1898: () => new AbortController(),
      _1899: x0 => x0.abort(),
      _1900: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1901: (x0,x1) => globalThis.fetch(x0,x1),
      _1902: (x0,x1) => x0.get(x1),
      _1903: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1903(f,arguments.length,x0,x1,x2) }),
      _1904: (x0,x1) => x0.forEach(x1),
      _1905: x0 => x0.getReader(),
      _1906: x0 => x0.cancel(),
      _1907: x0 => x0.read(),
      _1908: x0 => x0.trustedTypes,
      _1909: (x0,x1) => { x0.src = x1 },
      _1910: (x0,x1) => x0.createScriptURL(x1),
      _1911: x0 => x0.nonce,
      _1912: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1912(f,arguments.length,x0) }),
      _1913: x0 => ({createScriptURL: x0}),
      _1914: (x0,x1) => x0.querySelectorAll(x1),
      _1917: o => o instanceof Array,
      _1918: (a, i) => a.push(i),
      _1922: a => a.pop(),
      _1923: (a, i) => a.splice(i, 1),
      _1925: (a, s, e) => a.slice(s, e),
      _1927: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1928: a => a.length,
      _1930: (a, i) => a[i],
      _1931: (a, i, v) => a[i] = v,
      _1933: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1934: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1936: o => o instanceof Uint8Array,
      _1937: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1938: o => o instanceof Int8Array,
      _1939: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1940: o => o instanceof Uint8ClampedArray,
      _1941: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1942: o => o instanceof Uint16Array,
      _1943: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1944: o => o instanceof Int16Array,
      _1945: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1946: o => o instanceof Uint32Array,
      _1947: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1948: o => o instanceof Int32Array,
      _1949: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1951: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1952: o => o instanceof Float32Array,
      _1953: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1954: o => o instanceof Float64Array,
      _1955: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1956: (t, s) => t.set(s),
      _1957: l => new DataView(new ArrayBuffer(l)),
      _1958: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1959: o => o.byteLength,
      _1960: o => o.buffer,
      _1961: o => o.byteOffset,
      _1962: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1963: (b, o) => new DataView(b, o),
      _1964: (b, o, l) => new DataView(b, o, l),
      _1965: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1966: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1967: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1968: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1969: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1970: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1971: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1972: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1973: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1974: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1975: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1976: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1979: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1980: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1981: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1982: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1983: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1984: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1985: Function.prototype.call.bind(Number.prototype.toString),
      _1986: Function.prototype.call.bind(BigInt.prototype.toString),
      _1987: Function.prototype.call.bind(Number.prototype.toString),
      _1988: (d, digits) => d.toFixed(digits),
      _2046: () => globalThis.google.accounts.oauth2,
      _2047: (x0,x1,x2) => x0.hasGrantedAllScopes(x1,x2),
      _2048: (x0,x1) => x0.revoke(x1),
      _2049: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2049(f,arguments.length,x0) }),
      _2050: (x0,x1,x2) => x0.revoke(x1,x2),
      _2066: x0 => x0.access_token,
      _2067: x0 => x0.expires_in,
      _2073: x0 => x0.error,
      _2074: x0 => x0.error_description,
      _2076: x0 => x0.type,
      _2077: x0 => x0.message,
      _2081: () => globalThis.google.accounts.id,
      _2084: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2084(f,arguments.length,x0) }),
      _2085: (x0,x1) => x0.prompt(x1),
      _2095: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2095(f,arguments.length,x0) }),
      _2098: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _2102: x0 => x0.isSkippedMoment(),
      _2103: x0 => x0.isDismissedMoment(),
      _2107: x0 => x0.getDismissedReason(),
      _2109: x0 => x0.error,
      _2111: x0 => x0.credential,
      _2122: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2123: (module,f) => finalizeWrapper(f, function() { return module.exports._2123(f,arguments.length) }),
      _2172: (x0,x1) => { x0.responseType = x1 },
      _2173: x0 => x0.response,
      _2249: x0 => x0.style,
      _2448: (x0,x1) => { x0.nonce = x1 },
      _2608: (x0,x1) => { x0.download = x1 },
      _2633: (x0,x1) => { x0.href = x1 },
      _3178: (x0,x1) => { x0.accept = x1 },
      _3192: x0 => x0.files,
      _3218: (x0,x1) => { x0.multiple = x1 },
      _3236: (x0,x1) => { x0.type = x1 },
      _3486: (x0,x1) => { x0.src = x1 },
      _3488: (x0,x1) => { x0.type = x1 },
      _3492: (x0,x1) => { x0.async = x1 },
      _3494: (x0,x1) => { x0.defer = x1 },
      _3498: (x0,x1) => { x0.text = x1 },
      _3955: () => globalThis.window,
      _3995: x0 => x0.document,
      _4017: x0 => x0.navigator,
      _4272: x0 => x0.isSecureContext,
      _4275: x0 => x0.crypto,
      _4279: x0 => x0.trustedTypes,
      _4280: x0 => x0.sessionStorage,
      _4281: x0 => x0.localStorage,
      _4340: x0 => x0.message,
      _4404: x0 => x0.userAgent,
      _4405: x0 => x0.vendor,
      _4455: x0 => x0.data,
      _4485: x0 => x0.port1,
      _4486: x0 => x0.port2,
      _4490: (x0,x1) => { x0.onmessage = x1 },
      _4565: (x0,x1) => { x0.onerror = x1 },
      _4573: x0 => x0.port,
      _4575: (x0,x1) => { x0.onerror = x1 },
      _4608: x0 => x0.length,
      _6512: x0 => x0.type,
      _6553: x0 => x0.signal,
      _6562: x0 => x0.length,
      _6564: x0 => x0.length,
      _6621: () => globalThis.document,
      _6702: x0 => x0.body,
      _6704: x0 => x0.head,
      _7034: (x0,x1) => { x0.id = x1 },
      _7061: x0 => x0.children,
      _8380: x0 => x0.value,
      _8382: x0 => x0.done,
      _8546: x0 => x0.size,
      _8550: (x0,x1) => { x0.type = x1 },
      _8553: x0 => x0.name,
      _8554: x0 => x0.lastModified,
      _8559: x0 => x0.length,
      _8565: x0 => x0.result,
      _9061: x0 => x0.url,
      _9063: x0 => x0.status,
      _9065: x0 => x0.statusText,
      _9066: x0 => x0.headers,
      _9067: x0 => x0.body,
      _10521: x0 => x0.result,
      _10522: x0 => x0.error,
      _10533: (x0,x1) => { x0.onupgradeneeded = x1 },
      _10535: x0 => x0.oldVersion,
      _10614: x0 => x0.key,
      _10615: x0 => x0.primaryKey,
      _10617: x0 => x0.value,
      _11456: (x0,x1) => { x0.display = x1 },
      _12678: x0 => x0.name,
      _12679: x0 => x0.message,
      _12682: x0 => x0.subtle,
      _13386: () => globalThis.console,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
